#!/bin/bash
set -e

# H. liu, April 28, 2020.
# Run ensemble forcing generation year by year by generate_ensemble.exe.
# Depending on the existence of regression file generated by GMET downscaling code.
# Reference: /home/hydrofcst/otl_support/forcings/GMET/run/run_ens_forc.RETRO.csh
  
RootDir=/home/hongli/work/2020_04_21nldas_gmet

SourceDir=${RootDir}/scripts
GridInfo=${SourceDir}/conus_ens_grid_eighth_deg_v1p1.nc
StnlistDir=${SourceDir}/step4_sample_stnlist

Program=${RootDir}/GMET_tpl/run/generate_ensemble.exe
Template=${SourceDir}/config/namelist.ens_forc.TEMPLATE.txt 

startEns=1  # start number of ensembles to generate
stopEns=100  # stop number of ensembles to generate
sYear=2015 
eYear=2016

WorkDirBase=${RootDir}/test_uniform
if [ ! -d ${WorkDirBase} ]; then mkdir -p ${WorkDirBase}; fi

FILES=( $(ls ${StnlistDir}) )
FILE_NUM=${#FILES[@]}
# for i in $(seq 0 $(($FILE_NUM -1))); do
for i in $(seq 0 3); do
    
    FileName=${FILES[${i}]}
    FileNameShort="${FileName/.txt/}" # remove suffix ".txt"
    GridNum=$(echo $FileNameShort| cut -d'_' -f 2) # extract substring "012grids"    
    CaseID=${GridNum}
    echo ${CaseID}

    # create work folders
    WorkDir=${WorkDirBase}/${CaseID}
    if [ ! -d ${WorkDir} ]; then mkdir ${WorkDir}; fi
    if [ ! -d ${WorkDir}/tmp ]; then mkdir ${WorkDir}/tmp; fi
    if [ ! -d ${WorkDir}/gmet_ens ]; then mkdir ${WorkDir}/gmet_ens; fi
           
    # loop through years
    for Y in $(seq ${sYear} ${eYear}); do
        nDays=$(echo $Y | awk '{if($1%4==0){print 366}else{print 365}}') 
        echo $Y, $nDays
        
        # configure config, output and log files
        ConfigFile=${WorkDir}/tmp/namelist.ens_forc.$Y
        InRegrFile=${WorkDir}/gmet_regr/regress_ts.$Y.nc

        OutEnsForcRoot=${WorkDir}/gmet_ens/ens_forc.$Y
        rm -f $OutEnsForcRoot.*.nc
        
        sed "s,NDays,$nDays,g" $Template |\
        sed "s,StartEns,$startEns,g" |\
        sed "s,StopEns,$stopEns,g" |\
        sed "s,GridInfo,$GridInfo,g" |\
        sed "s,InRegrFile,$InRegrFile,g" |\
        sed "s,OutEnsForcRoot,$OutEnsForcRoot,g" > $ConfigFile

        # create job submission file
        CommandFile=${WorkDir}/tmp/sbatch.ens_forc.$Y
        if [ -e ${command_file} ]; then rm -rf ${command_file}; fi
        
        LogFile=${WorkDir}/tmp/log.ens_forc.$Y
        rm -f $LogFile.*

        echo '#!/bin/bash' > ${CommandFile}
        echo "#SBATCH --job-name=ens.${CaseID}.${Y}" >> ${CommandFile}
        echo '#SBATCH --partition=main' >> ${CommandFile}
        echo '#SBATCH --ntasks=1' >> ${CommandFile}
        echo '#SBATCH --time=999:00:00' >> ${CommandFile}
        echo "#SBATCH --output=${LogFile}.%j" >> ${CommandFile}

        echo "${Program} ${ConfigFile}" >> ${CommandFile}
        chmod 740 ${CommandFile}
        
        sbatch ${CommandFile}
        
     done
done

